FROM python:3.8.3-alpine

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update && apk add cmake gcc python3-dev

RUN pip install -U pip
COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir

COPY . .